local M = {}

local ext_to_lang = {
    lua = "lua", py = "python", js = "javascript", ts = "typescript",
    tsx = "tsx", jsx = "jsx", rs = "rust", go = "go", rb = "ruby",
    java = "java", kt = "kotlin", c = "c", cpp = "cpp", h = "c",
    sh = "bash", sql = "sql", yml = "yaml", yaml = "yaml",
    json = "json", toml = "toml", vim = "vim",
}

function M.get_repo_root()
    local result = vim.fn.systemlist("git rev-parse --show-toplevel")
    if vim.v.shell_error ~= 0 then return nil end
    return result[1]
end

function M.review_path(repo_root, filename)
    return repo_root .. "/" .. filename
end

local function lang_for_file(filepath)
    local ext = filepath:match("%.([^%.]+)$")
    return ext and ext_to_lang[ext] or ""
end

local function read_context(repo_root, file, start_line, end_line)
    local full_path = repo_root .. "/" .. file
    local ok, lines = pcall(vim.fn.readfile, full_path)
    if not ok or not lines then return nil end
    local result = {}
    for i = start_line, math.min(end_line, #lines) do
        table.insert(result, lines[i])
    end
    if #result == 0 then return nil end
    return result
end

function M.serialize(comments_list, repo_root, filename)
    if #comments_list == 0 then
        local path = M.review_path(repo_root, filename)
        if vim.fn.filereadable(path) == 1 then
            vim.fn.delete(path)
        end
        return nil
    end

    local path = M.review_path(repo_root, filename)
    local out = { "<!-- marginalia review — generated by marginalia.nvim -->", "" }

    local sorted = vim.deepcopy(comments_list)
    table.sort(sorted, function(a, b)
        if a.file ~= b.file then return a.file < b.file end
        return a.line < b.line
    end)

    for i, c in ipairs(sorted) do
        local anchor = c.line_end
            and string.format("%s:%d-%d", c.file, c.line, c.line_end)
            or string.format("%s:%d", c.file, c.line)
        table.insert(out, "## " .. anchor)
        table.insert(out, "")

        table.insert(out, "Status: " .. (c.status or "open"))
        table.insert(out, "")

        local ctx_start = c.line
        local ctx_end = c.line_end or c.line
        local ctx_lines = read_context(repo_root, c.file, ctx_start, ctx_end)
        if ctx_lines then
            local lang = lang_for_file(c.file)
            table.insert(out, "Context:")
            table.insert(out, "```" .. lang)
            for _, l in ipairs(ctx_lines) do
                table.insert(out, l)
            end
            table.insert(out, "```")
            table.insert(out, "")
        end

        table.insert(out, "Comment:")
        for _, l in ipairs(vim.split(c.body, "\n", { plain = true })) do
            table.insert(out, l)
        end

        if i < #sorted then
            table.insert(out, "")
            table.insert(out, "---")
            table.insert(out, "")
        else
            table.insert(out, "")
        end
    end

    vim.fn.writefile(out, path)
    return path
end

function M.parse(filepath)
    local ok, lines = pcall(vim.fn.readfile, filepath)
    if not ok or not lines then return nil, "Cannot read file: " .. filepath end

    local entries = {}
    local current = nil
    local state = "idle"
    local in_code_fence = false
    local body_lines = {}

    local function emit()
        if current then
            current.body = vim.fn.trim(table.concat(body_lines, "\n"))
            if current.body ~= "" then
                table.insert(entries, current)
            end
            current = nil
            body_lines = {}
        end
    end

    local function try_header(line)
        local file, s, e = line:match("^## (.+):(%d+)-(%d+)%s*$")
        if file then
            return { file = file, line = tonumber(s), line_end = tonumber(e), status = "open" }
        end
        file, s = line:match("^## (.+):(%d+)%s*$")
        if file then
            return { file = file, line = tonumber(s), status = "open" }
        end
        return nil
    end

    for _, line in ipairs(lines) do
        if state == "idle" then
            local header = try_header(line)
            if header then
                current = header
                state = "header"
            end

        elseif state == "header" then
            local status = line:match("^Status:%s*(%S+)")
            if status then
                current.status = status
                state = "status"
            end

        elseif state == "status" then
            if line:match("^Context:") then
                state = "context"
                in_code_fence = false
            elseif line:match("^Comment:") then
                state = "comment"
                body_lines = {}
            end

        elseif state == "context" then
            if line:match("^Comment:") then
                state = "comment"
                body_lines = {}
                in_code_fence = false
            elseif line:match("^```") then
                in_code_fence = not in_code_fence
            end

        elseif state == "comment" then
            local header = try_header(line)
            if line:match("^%-%-%-$") then
                emit()
                state = "idle"
            elseif header then
                emit()
                current = header
                state = "header"
            else
                table.insert(body_lines, line)
            end
        end
    end

    emit()
    return entries
end

function M.ensure_gitignore(review_filename)
    local ignore_file = vim.fn.expand("~/.config/git/ignore")

    local lines = {}
    local ok, existing = pcall(vim.fn.readfile, ignore_file)
    if ok and existing then
        for _, l in ipairs(existing) do
            if vim.fn.trim(l) == review_filename then
                return
            end
        end
        lines = existing
    end

    vim.ui.select(
        { "Yes, add to global gitignore", "No, I'll handle it" },
        { prompt = review_filename .. " is not in your global gitignore. Add it?" },
        function(choice)
            if not choice or choice:match("^No") then return end
            table.insert(lines, review_filename)
            vim.fn.mkdir(vim.fn.fnamemodify(ignore_file, ":h"), "p")
            vim.fn.writefile(lines, ignore_file)
            vim.notify("marginalia: added " .. review_filename .. " to " .. ignore_file, vim.log.levels.INFO)
        end
    )
end

return M
