local MiniTest = require('mini.test')
local new_set = MiniTest.new_set

local T = new_set()

local review_file
local tmpdir

T['setup'] = new_set({
    hooks = {
        pre_case = function()
            package.loaded['marginalia.review_file'] = nil
            review_file = require('marginalia.review_file')
            tmpdir = vim.fn.tempname()
            vim.fn.mkdir(tmpdir, "p")
        end,
        post_case = function()
            if tmpdir then
                vim.fn.delete(tmpdir, "rf")
            end
        end,
    },
})

-- Helper: write a source file in the fake repo so context can be read
local function write_source(repo_root, rel_path, lines)
    local dir = vim.fn.fnamemodify(repo_root .. "/" .. rel_path, ":h")
    vim.fn.mkdir(dir, "p")
    vim.fn.writefile(lines, repo_root .. "/" .. rel_path)
end

-- ── serialize ────────────────────────────────────────────────────────

T['setup']['serialize single comment produces correct format'] = function()
    write_source(tmpdir, "src/foo.lua", {
        "local M = {}",
        "function M.run()",
        "  return 42",
        "end",
        "return M",
    })

    local comments = {
        { file = "src/foo.lua", line = 3, body = "Magic number", status = "open" },
    }

    local path = review_file.serialize(comments, tmpdir, "REVIEW.md")
    MiniTest.expect.equality(path, tmpdir .. "/REVIEW.md")

    local lines = vim.fn.readfile(path)
    local content = table.concat(lines, "\n")

    -- Header
    MiniTest.expect.equality(lines[1], "<!-- marginalia review — generated by marginalia.nvim -->")
    -- Anchor
    assert(content:find("## src/foo.lua:3"), "missing header anchor")
    -- Status
    assert(content:find("Status: open"), "missing status")
    -- Context
    assert(content:find("```lua"), "missing code fence lang")
    assert(content:find("return 42"), "missing context line")
    -- Comment body
    assert(content:find("Comment:\nMagic number"), "missing comment body")
end

T['setup']['serialize range comment uses start-end anchor'] = function()
    write_source(tmpdir, "app.py", {
        "def run():",
        "    x = 1",
        "    y = 2",
        "    return x + y",
    })

    local comments = {
        { file = "app.py", line = 2, line_end = 3, body = "Rename these", status = "open" },
    }

    review_file.serialize(comments, tmpdir, "REVIEW.md")
    local lines = vim.fn.readfile(tmpdir .. "/REVIEW.md")
    local content = table.concat(lines, "\n")

    assert(content:find("## app.py:2%-3"), "missing range anchor")
    assert(content:find("```python"), "missing python lang hint")
    assert(content:find("x = 1"), "missing first context line")
    assert(content:find("y = 2"), "missing second context line")
end

T['setup']['serialize multiple comments sorted by file then line'] = function()
    write_source(tmpdir, "b.lua", { "b1", "b2" })
    write_source(tmpdir, "a.lua", { "a1", "a2", "a3" })

    local comments = {
        { file = "b.lua", line = 1, body = "B comment", status = "open" },
        { file = "a.lua", line = 3, body = "A line 3", status = "open" },
        { file = "a.lua", line = 1, body = "A line 1", status = "resolved" },
    }

    review_file.serialize(comments, tmpdir, "REVIEW.md")
    local lines = vim.fn.readfile(tmpdir .. "/REVIEW.md")
    local content = table.concat(lines, "\n")

    local pos_a1 = content:find("## a.lua:1")
    local pos_a3 = content:find("## a.lua:3")
    local pos_b1 = content:find("## b.lua:1")
    assert(pos_a1 and pos_a3 and pos_b1, "missing anchors")
    assert(pos_a1 < pos_a3, "a.lua:1 should come before a.lua:3")
    assert(pos_a3 < pos_b1, "a.lua should come before b.lua")
    assert(content:find("Status: resolved"), "resolved status not preserved")
end

T['setup']['serialize empty list deletes existing file'] = function()
    local path = tmpdir .. "/REVIEW.md"
    vim.fn.writefile({ "old content" }, path)
    MiniTest.expect.equality(vim.fn.filereadable(path), 1)

    review_file.serialize({}, tmpdir, "REVIEW.md")
    MiniTest.expect.equality(vim.fn.filereadable(path), 0)
end

T['setup']['serialize empty list returns nil when no file exists'] = function()
    local result = review_file.serialize({}, tmpdir, "REVIEW.md")
    MiniTest.expect.equality(result, nil)
end

T['setup']['serialize with missing source file omits context'] = function()
    local comments = {
        { file = "nonexistent.lua", line = 5, body = "Still works", status = "open" },
    }

    review_file.serialize(comments, tmpdir, "REVIEW.md")
    local lines = vim.fn.readfile(tmpdir .. "/REVIEW.md")
    local content = table.concat(lines, "\n")

    assert(content:find("## nonexistent.lua:5"), "missing anchor")
    assert(content:find("Comment:\nStill works"), "missing body")
    assert(not content:find("Context:"), "should not have context block")
end

-- ── parse ────────────────────────────────────────────────────────────

T['setup']['parse single comment'] = function()
    vim.fn.writefile({
        "<!-- marginalia review — generated by marginalia.nvim -->",
        "",
        "## src/foo.lua:42",
        "",
        "Status: open",
        "",
        "Context:",
        "```lua",
        "    local x = 1",
        "```",
        "",
        "Comment:",
        "Rename this variable",
        "",
    }, tmpdir .. "/REVIEW.md")

    local entries = review_file.parse(tmpdir .. "/REVIEW.md")
    MiniTest.expect.equality(#entries, 1)
    MiniTest.expect.equality(entries[1].file, "src/foo.lua")
    MiniTest.expect.equality(entries[1].line, 42)
    MiniTest.expect.equality(entries[1].line_end, nil)
    MiniTest.expect.equality(entries[1].status, "open")
    MiniTest.expect.equality(entries[1].body, "Rename this variable")
end

T['setup']['parse range comment'] = function()
    vim.fn.writefile({
        "## app.py:10-15",
        "",
        "Status: resolved",
        "",
        "Comment:",
        "This block needs refactoring",
        "",
    }, tmpdir .. "/REVIEW.md")

    local entries = review_file.parse(tmpdir .. "/REVIEW.md")
    MiniTest.expect.equality(#entries, 1)
    MiniTest.expect.equality(entries[1].file, "app.py")
    MiniTest.expect.equality(entries[1].line, 10)
    MiniTest.expect.equality(entries[1].line_end, 15)
    MiniTest.expect.equality(entries[1].status, "resolved")
end

T['setup']['parse multiple comments with separator'] = function()
    vim.fn.writefile({
        "## a.lua:1",
        "",
        "Status: open",
        "",
        "Comment:",
        "First",
        "",
        "---",
        "",
        "## a.lua:5",
        "",
        "Status: resolved",
        "",
        "Comment:",
        "Second",
        "",
    }, tmpdir .. "/REVIEW.md")

    local entries = review_file.parse(tmpdir .. "/REVIEW.md")
    MiniTest.expect.equality(#entries, 2)
    MiniTest.expect.equality(entries[1].body, "First")
    MiniTest.expect.equality(entries[1].status, "open")
    MiniTest.expect.equality(entries[2].body, "Second")
    MiniTest.expect.equality(entries[2].status, "resolved")
end

T['setup']['parse multi-line comment body'] = function()
    vim.fn.writefile({
        "## foo.rs:7",
        "",
        "Status: open",
        "",
        "Comment:",
        "Line one",
        "",
        "Line three after blank",
        "",
    }, tmpdir .. "/REVIEW.md")

    local entries = review_file.parse(tmpdir .. "/REVIEW.md")
    MiniTest.expect.equality(#entries, 1)
    MiniTest.expect.equality(entries[1].body, "Line one\n\nLine three after blank")
end

T['setup']['parse without context block'] = function()
    vim.fn.writefile({
        "## gone.lua:99",
        "",
        "Status: open",
        "",
        "Comment:",
        "File was deleted",
        "",
    }, tmpdir .. "/REVIEW.md")

    local entries = review_file.parse(tmpdir .. "/REVIEW.md")
    MiniTest.expect.equality(#entries, 1)
    MiniTest.expect.equality(entries[1].body, "File was deleted")
end

T['setup']['parse returns nil for missing file'] = function()
    local entries, err = review_file.parse(tmpdir .. "/nope.md")
    MiniTest.expect.equality(entries, nil)
    assert(err:find("Cannot read"), "expected error message")
end

-- ── round-trip ───────────────────────────────────────────────────────

T['setup']['round-trip preserves comment data'] = function()
    write_source(tmpdir, "lib.lua", {
        "-- header",
        "local M = {}",
        "function M.go() end",
        "return M",
    })

    local original = {
        { file = "lib.lua", line = 2, body = "Add docstring", status = "open" },
        { file = "lib.lua", line = 3, line_end = 3, body = "Needs error handling\nand logging", status = "resolved" },
    }

    review_file.serialize(original, tmpdir, "REVIEW.md")
    local parsed = review_file.parse(tmpdir .. "/REVIEW.md")

    MiniTest.expect.equality(#parsed, 2)

    MiniTest.expect.equality(parsed[1].file, "lib.lua")
    MiniTest.expect.equality(parsed[1].line, 2)
    MiniTest.expect.equality(parsed[1].body, "Add docstring")
    MiniTest.expect.equality(parsed[1].status, "open")

    MiniTest.expect.equality(parsed[2].file, "lib.lua")
    MiniTest.expect.equality(parsed[2].line, 3)
    MiniTest.expect.equality(parsed[2].line_end, 3)
    MiniTest.expect.equality(parsed[2].body, "Needs error handling\nand logging")
    MiniTest.expect.equality(parsed[2].status, "resolved")
end

T['setup']['round-trip with multiple files'] = function()
    write_source(tmpdir, "a.py", { "def a(): pass" })
    write_source(tmpdir, "z.py", { "def z(): pass" })

    local original = {
        { file = "z.py", line = 1, body = "Z comment", status = "open" },
        { file = "a.py", line = 1, body = "A comment", status = "open" },
    }

    review_file.serialize(original, tmpdir, "REVIEW.md")
    local parsed = review_file.parse(tmpdir .. "/REVIEW.md")

    MiniTest.expect.equality(#parsed, 2)
    -- serialize sorts by file, so a.py comes first
    MiniTest.expect.equality(parsed[1].file, "a.py")
    MiniTest.expect.equality(parsed[2].file, "z.py")
end

return T
